#===========================
# hap-nature-remo 設定ファイル
#===========================

## アクセストークン(必須)
## 下記サイトを参考に事前に取得して、起動前に設定しておいてください。
## https://developer.nature.global/#oauth2
token: 

## ブリッジ名(デフォルト: hap-nature-remo)
# name: hap-nature-remo 

## HomeKit PINコード(デフォルト: 12344321)
## 指定する場合、必ず " で括って書いてください
# pin: "12344321"
